/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculatorproject;

import javax.swing.JOptionPane;

/**
 *
 * @author Avishek
 */
public class Calculator extends javax.swing.JFrame {
    private static String str = "";
    private static String str0 = "";
    private static String act = "";
    private static double num1 = 0;
    private static double num2 = 0;
    private static double res = 0;
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        zero = new javax.swing.JButton();
        point = new javax.swing.JButton();
        pi = new javax.swing.JButton();
        one = new javax.swing.JButton();
        two = new javax.swing.JButton();
        three = new javax.swing.JButton();
        four = new javax.swing.JButton();
        five = new javax.swing.JButton();
        six = new javax.swing.JButton();
        seven = new javax.swing.JButton();
        eight = new javax.swing.JButton();
        nine = new javax.swing.JButton();
        squareroot = new javax.swing.JButton();
        cubicroot = new javax.swing.JButton();
        power = new javax.swing.JButton();
        square = new javax.swing.JButton();
        cube = new javax.swing.JButton();
        absolute = new javax.swing.JButton();
        sine = new javax.swing.JButton();
        cosine = new javax.swing.JButton();
        tangent = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        equal = new javax.swing.JButton();
        plus = new javax.swing.JButton();
        minus = new javax.swing.JButton();
        multiply = new javax.swing.JButton();
        div = new javax.swing.JButton();
        mod = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        tf1 = new javax.swing.JTextField();
        tf2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setLayout(null);

        zero.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        zero.setText("0");
        zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroActionPerformed(evt);
            }
        });
        jPanel3.add(zero);
        zero.setBounds(0, 500, 90, 50);

        point.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        point.setText(".");
        point.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pointActionPerformed(evt);
            }
        });
        jPanel3.add(point);
        point.setBounds(100, 500, 90, 50);

        pi.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        pi.setText("PI");
        pi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piActionPerformed(evt);
            }
        });
        jPanel3.add(pi);
        pi.setBounds(200, 500, 90, 50);

        one.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        one.setText("1");
        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneActionPerformed(evt);
            }
        });
        jPanel3.add(one);
        one.setBounds(0, 440, 90, 50);

        two.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        two.setText("2");
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoActionPerformed(evt);
            }
        });
        jPanel3.add(two);
        two.setBounds(100, 440, 90, 50);

        three.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        three.setText("3");
        three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeActionPerformed(evt);
            }
        });
        jPanel3.add(three);
        three.setBounds(200, 440, 90, 50);

        four.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        four.setText("4");
        four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourActionPerformed(evt);
            }
        });
        jPanel3.add(four);
        four.setBounds(0, 380, 90, 50);

        five.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        five.setText("5");
        five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveActionPerformed(evt);
            }
        });
        jPanel3.add(five);
        five.setBounds(100, 380, 90, 50);

        six.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        six.setText("6");
        six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixActionPerformed(evt);
            }
        });
        jPanel3.add(six);
        six.setBounds(200, 380, 90, 50);

        seven.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        seven.setText("7");
        seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenActionPerformed(evt);
            }
        });
        jPanel3.add(seven);
        seven.setBounds(0, 320, 90, 50);

        eight.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        eight.setText("8");
        eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightActionPerformed(evt);
            }
        });
        jPanel3.add(eight);
        eight.setBounds(100, 320, 90, 50);

        nine.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        nine.setText("9");
        nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineActionPerformed(evt);
            }
        });
        jPanel3.add(nine);
        nine.setBounds(200, 320, 90, 50);

        squareroot.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        squareroot.setText("sqrt");
        squareroot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                squarerootActionPerformed(evt);
            }
        });
        jPanel3.add(squareroot);
        squareroot.setBounds(0, 260, 90, 50);

        cubicroot.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cubicroot.setText("cbrt");
        cubicroot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cubicrootActionPerformed(evt);
            }
        });
        jPanel3.add(cubicroot);
        cubicroot.setBounds(100, 260, 90, 50);

        power.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        power.setText("^");
        power.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powerActionPerformed(evt);
            }
        });
        jPanel3.add(power);
        power.setBounds(200, 260, 90, 50);

        square.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        square.setText("<html>\nx<sup>2</sup>\n</html>");
        square.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                squareActionPerformed(evt);
            }
        });
        jPanel3.add(square);
        square.setBounds(0, 200, 90, 50);

        cube.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cube.setText("<html>\nx<sup>3</sup>\n</html>");
        cube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cubeActionPerformed(evt);
            }
        });
        jPanel3.add(cube);
        cube.setBounds(100, 200, 90, 50);

        absolute.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        absolute.setText("abs");
        absolute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                absoluteActionPerformed(evt);
            }
        });
        jPanel3.add(absolute);
        absolute.setBounds(200, 200, 90, 50);

        sine.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        sine.setText("sin");
        sine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sineActionPerformed(evt);
            }
        });
        jPanel3.add(sine);
        sine.setBounds(0, 140, 90, 50);

        cosine.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cosine.setText("cos");
        cosine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosineActionPerformed(evt);
            }
        });
        jPanel3.add(cosine);
        cosine.setBounds(100, 140, 90, 50);

        tangent.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tangent.setText("tan");
        tangent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tangentActionPerformed(evt);
            }
        });
        jPanel3.add(tangent);
        tangent.setBounds(200, 140, 90, 50);

        jPanel4.setBackground(new java.awt.Color(153, 0, 153));
        jPanel4.setLayout(null);

        equal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        equal.setText("=");
        equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalActionPerformed(evt);
            }
        });
        jPanel4.add(equal);
        equal.setBounds(0, 360, 130, 60);

        plus.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        plus.setText("+");
        plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusActionPerformed(evt);
            }
        });
        jPanel4.add(plus);
        plus.setBounds(0, 310, 130, 50);

        minus.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        minus.setText("-");
        minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusActionPerformed(evt);
            }
        });
        jPanel4.add(minus);
        minus.setBounds(0, 260, 130, 50);

        multiply.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        multiply.setText("X");
        multiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyActionPerformed(evt);
            }
        });
        jPanel4.add(multiply);
        multiply.setBounds(0, 210, 130, 50);

        div.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        div.setText("/");
        div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divActionPerformed(evt);
            }
        });
        jPanel4.add(div);
        div.setBounds(0, 160, 130, 50);

        mod.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mod.setText("%");
        mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modActionPerformed(evt);
            }
        });
        jPanel4.add(mod);
        mod.setBounds(0, 110, 130, 50);

        clear.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel4.add(clear);
        clear.setBounds(0, 10, 130, 50);

        back.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel4.add(back);
        back.setBounds(0, 60, 130, 50);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(300, 130, 140, 430);

        jPanel2.setLayout(null);

        tf1.setBackground(new java.awt.Color(0, 153, 102));
        tf1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel2.add(tf1);
        tf1.setBounds(10, 60, 440, 80);

        tf2.setBackground(new java.awt.Color(0, 153, 204));
        tf2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel2.add(tf2);
        tf2.setBounds(10, 0, 440, 80);

        jPanel3.add(jPanel2);
        jPanel2.setBounds(-10, 0, 450, 130);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 440, 560);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusActionPerformed
        // TODO add your handling code here:

        String str1 = tf1.getText();
        if(str1.equals(""))
        {
            tf1.setText(plus.getText());
        }
        else
        {
            num1 = Double.valueOf(tf1.getText());
            act = plus.getText();
            tf2.setText(String.valueOf(num1) + " " + act);
            tf1.setText("");
        }
 
    }//GEN-LAST:event_plusActionPerformed

    private void fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveActionPerformed
        // TODO add your handling code here:
        str = tf1.getText() + five.getText();
        tf1.setText(str);
    }//GEN-LAST:event_fiveActionPerformed

    private void eightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightActionPerformed
        // TODO add your handling code here:
        str = tf1.getText() + eight.getText();
        tf1.setText(str);
    }//GEN-LAST:event_eightActionPerformed

    private void twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoActionPerformed
        // TODO add your handling code here:
        str = tf1.getText() + two.getText();
        tf1.setText(str);
    }//GEN-LAST:event_twoActionPerformed

    private void divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divActionPerformed
        // TODO add your handling code here:
            num1 = Double.valueOf(tf1.getText());
            act = div.getText();
            tf2.setText(String.valueOf(num1) + " " + act);
            tf1.setText("");
    }//GEN-LAST:event_divActionPerformed

    private void oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneActionPerformed
        // TODO add your handling code here:
        str = tf1.getText() + one.getText();
        tf1.setText(str);
        
    }//GEN-LAST:event_oneActionPerformed

    private void zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroActionPerformed
        // TODO add your handling code here:
        str = tf1.getText() + zero.getText();
        tf1.setText(str);
        
    }//GEN-LAST:event_zeroActionPerformed

    private void pointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pointActionPerformed
        // TODO add your handling code here
        str = tf1.getText() + point.getText();
        tf1.setText(str);
    }//GEN-LAST:event_pointActionPerformed

    private void piActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piActionPerformed
        // TODO add your handling code here:
        str = tf1.getText() + String.valueOf(Math.PI);
        tf1.setText(str);
    }//GEN-LAST:event_piActionPerformed

    private void threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeActionPerformed
        // TODO add your handling code here:
        str = tf1.getText() + three.getText();
        tf1.setText(str);
    }//GEN-LAST:event_threeActionPerformed

    private void fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourActionPerformed
        // TODO add your handling code here:
        str = tf1.getText() + four.getText();
        tf1.setText(str);
    }//GEN-LAST:event_fourActionPerformed

    private void sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixActionPerformed
        // TODO add your handling code here:
        str = tf1.getText() + six.getText();
        tf1.setText(str);
    }//GEN-LAST:event_sixActionPerformed

    private void squarerootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_squarerootActionPerformed
        // TODO add your handling code here:
        String str1 = tf1.getText();
        if(str1.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please enter some value first !! ");
        }
        else
        {
            num1 = Double.valueOf(tf1.getText());
            tf1.setText( String.valueOf( Math.sqrt(num1)));
            tf2.setText("Square root of " + String.valueOf(num1) + " = ");
        }
    }//GEN-LAST:event_squarerootActionPerformed

    private void cubicrootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cubicrootActionPerformed
        // TODO add your handling code here:
        String str1 = tf1.getText();
        if(str1.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please enter some value first !! ");
        }
        else
        {
            num1 = Double.valueOf(tf1.getText());
            tf1.setText( String.valueOf( Math.pow(num1,0.33333333)));
            tf2.setText("Cubic root of " + String.valueOf(num1) + " = ");
        }
    }//GEN-LAST:event_cubicrootActionPerformed

    private void powerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powerActionPerformed
        // TODO add your handling code here:
        num1 = Double.valueOf(tf1.getText());
        act = "^";
        tf2.setText(String.valueOf(num1) + " " + power.getText());
        tf1.setText("");
        
    }//GEN-LAST:event_powerActionPerformed

    private void squareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_squareActionPerformed
        // TODO add your handling code here:
        String str1 = tf1.getText();
        if(str1.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please enter some value first !! ");
        }
        else
        {
            num1 = Double.valueOf(tf1.getText());
            tf1.setText( String.valueOf( Math.pow(num1,2)));
            tf2.setText("Square of " + String.valueOf(num1) + " = ");
        }
    }//GEN-LAST:event_squareActionPerformed

    private void cubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cubeActionPerformed
        // TODO add your handling code here:
        String str1 = tf1.getText();
        if(str1.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please enter some value FIRST !! ");
        }
        else
        {
            num1 = Double.valueOf(tf1.getText());
            tf1.setText( String.valueOf( Math.pow(num1,3)));
            tf2.setText("Cube of " + String.valueOf(num1) + " = ");
        }
    }//GEN-LAST:event_cubeActionPerformed

    private void absoluteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_absoluteActionPerformed
        // TODO add your handling code here:
        str = tf1.getText();
        if(str.equals(""))
        {
           JOptionPane.showMessageDialog(null,"Please enter some value FIRST !! ");
        }
        else
        {
            num1 = Double.valueOf(tf1.getText());
            tf2.setText("|" + tf1.getText() + "| = ");
            tf1.setText(String.valueOf(Math.abs(num1)));
        }
    }//GEN-LAST:event_absoluteActionPerformed

    private void sineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sineActionPerformed
        // TODO add your handling code here:
        String str1 = tf1.getText();
        if(str1.equals(""))
        {
           tf1.setText("");
           tf2.setText(sine.getText());
           act = "sin";
        }
        else
        {
            JOptionPane.showMessageDialog(null,"First clear the display !! ");
        }
    }//GEN-LAST:event_sineActionPerformed

    private void cosineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosineActionPerformed
        // TODO add your handling code here:
        String str1 = tf1.getText();
        if(str1.equals(""))
        {
           tf1.setText("");
           tf2.setText(cosine.getText());
           act = "cos";
        }
        else
        {
            JOptionPane.showMessageDialog(null,"First clear the display !! ");
        }
    }//GEN-LAST:event_cosineActionPerformed

    private void tangentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tangentActionPerformed
        // TODO add your handling code here:
        String str1 = tf1.getText();
        if(str1.equals(""))
        {
           tf1.setText("");
           tf2.setText(tangent.getText());
           act = "tan";
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Please clear the display First !! ");
        }
    }//GEN-LAST:event_tangentActionPerformed

    private void minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusActionPerformed
        // TODO add your handling code here:
        String str1 = tf1.getText();
        if(str1.equals(""))
        {
            tf1.setText(minus.getText());
        }
        else
        {
            num1 = Double.valueOf(tf1.getText());
            act = minus.getText();
            tf2.setText(String.valueOf(num1) + " " + act);
            tf1.setText("");
        }
 
    }//GEN-LAST:event_minusActionPerformed

    private void multiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyActionPerformed
        // TODO add your handling code here:
            num1 = Double.valueOf(tf1.getText());
            act = multiply.getText();
            tf2.setText(String.valueOf(num1) + " " + act);
            tf1.setText("");
    }//GEN-LAST:event_multiplyActionPerformed

    private void modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modActionPerformed
        // TODO add your handling code here:
            num1 = Double.valueOf(tf1.getText());
            act = mod.getText();
            tf2.setText(String.valueOf(num1) + " " + act);
            tf1.setText("");
    }//GEN-LAST:event_modActionPerformed

    private void equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalActionPerformed
        // TODO add your handling code here:
        num2 = Double.valueOf(tf1.getText());
        str0 = tf2.getText() + " " + String.valueOf(num2) + " = " ;
        tf2.setText(str0);

            if(act.equals("+"))
            {
                res = num1 + num2;
            }
            else if(act.equals("-"))
            {
                res = num1 - num2;
            }
            else if(act.equals("X"))
            {
                res = num1 * num2;
            }
            else if(act.equals("/"))
            {
                res = num1 / num2;
            }
            else if(act.equals("%"))
            {
                res = num1 % num2;
            }
            else if(act.equals("sin"))
            {
                res = Math.sin( Math.toRadians(num2));
            }
            else if(act.equals("cos"))
            {
                res = Math.cos( Math.toRadians(num2));
            }
            else if(act.equals("tan"))
            {
                res = Math.tan( Math.toRadians(num2));
            }
            else if(act.equals("^"))
            {
                res = Math.pow(num1,num2);
            }
            tf1.setText(String.valueOf(res));
 
    }//GEN-LAST:event_equalActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        str = tf1.getText();
        str = str.substring(0,(str.length()-1) );
        tf1.setText(str);
    }//GEN-LAST:event_backActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        tf1.setText("");
        tf2.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void nineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineActionPerformed
        // TODO add your handling code here:
        str = tf1.getText() + nine.getText();
        tf1.setText(str);
    }//GEN-LAST:event_nineActionPerformed

    private void sevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenActionPerformed
        // TODO add your handling code here:
        str = tf1.getText() + seven.getText();
        tf1.setText(str);
    }//GEN-LAST:event_sevenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton absolute;
    private javax.swing.JButton back;
    private javax.swing.JButton clear;
    private javax.swing.JButton cosine;
    private javax.swing.JButton cube;
    private javax.swing.JButton cubicroot;
    private javax.swing.JButton div;
    private javax.swing.JButton eight;
    private javax.swing.JButton equal;
    private javax.swing.JButton five;
    private javax.swing.JButton four;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton minus;
    private javax.swing.JButton mod;
    private javax.swing.JButton multiply;
    private javax.swing.JButton nine;
    private javax.swing.JButton one;
    private javax.swing.JButton pi;
    private javax.swing.JButton plus;
    private javax.swing.JButton point;
    private javax.swing.JButton power;
    private javax.swing.JButton seven;
    private javax.swing.JButton sine;
    private javax.swing.JButton six;
    private javax.swing.JButton square;
    private javax.swing.JButton squareroot;
    private javax.swing.JButton tangent;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JButton three;
    private javax.swing.JButton two;
    private javax.swing.JButton zero;
    // End of variables declaration//GEN-END:variables
}
